import { inter } from "@/lib/fonts";
import "./globals.css";
import Providers from "./providers";
import { Toaster } from "react-hot-toast";
import AuthInitializer from "@/components/AuthInitializer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`h-full antialiased`}
    >
      <body className={`${inter.className} min-h-full flex flex-col`}>
        <Providers>
          <AuthInitializer />
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
